name: Lint
on:
  push:
    branches:
      - rn-74
  pull_request:
    branches:
      - rn-74

jobs:
  build:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
